### ISSUE TITLE
Unable to setup operator sdk 1.6.2

### ISSUE THREAD

**Issue by planetf1** [shivanshs9/setup-k8s-operator-sdk#6]
I tried using the action to setup operator sdk 1.6.2 ie:
```
- name: set up OperatorSDK
   uses: shivanshs9/setup-k8s-operator-sdk@v1
   with:
     version: "1.6.2"
```
but my action run at https://github.com/odpi/egeria-k8s-operator/runs/2419567084?check_suite_focus=true failed with 
```
Run shivanshs9/setup-k8s-operator-sdk@v1
  with:
    version: 1.6.2
  env:
    GO111MODULE: on
    CGO_ENABLED: 1
    GOROOT: /opt/hostedtoolcache/go/1.15.11/x64
Error: File not found: '/home/runner/work/_actions/shivanshs9/setup-k8s-operator-sdk/v1/dist/index.js'
```
